spring:
  cloud:
    stream:
      bindings:
        output:
          destination: tp-kinesis-stream
          content-type: text/plain

cloud:
  aws:
    credentials:
      accessKey: AKIAQQABACRM44EKZCXC
      secretKey: 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
    region:
      static: us-east-1
    stack:
      auto: false